# Generated by Django 4.2 on 2023-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_bloguploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguploadmodel',
            name='blogername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
