# Generated by Django 4.2 on 2023-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_bloguploadmodel_blogername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='serverapp/static/blogImages'),
            preserve_default=False,
        ),
    ]
