# Generated by Django 4.2 on 2023-05-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_alter_bloguploadmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='trailupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig', models.FileField(upload_to='serverapp/static')),
            ],
        ),
    ]
