# Generated by Django 4.2 on 2023-05-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0005_trailupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailupload',
            name='ig',
            field=models.ImageField(upload_to='serverapp/static'),
        ),
    ]
