# Generated by Django 4.2 on 2023-05-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0006_alter_trailupload_ig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trailupload',
        ),
    ]
