# Generated by Django 4.2 on 2023-05-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0007_delete_trailupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguploadmodel',
            old_name='blogername',
            new_name='blogerName',
        ),
    ]
