# Generated by Django 4.2 on 2023-05-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0008_rename_blogername_bloguploadmodel_blogername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguploadmodel',
            old_name='blogerName',
            new_name='blogername',
        ),
    ]
