# Generated by Django 4.2 on 2023-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0009_rename_blogername_bloguploadmodel_blogername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphFirst',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphSecond',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
