# Generated by Django 4.2 on 2023-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0010_alter_bloguploadmodel_paragarphfirst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphSecond',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='subTitleNameSecond',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
