# Generated by Django 4.2 on 2023-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0012_alter_bloguploadmodel_paragarphfirst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default=1, upload_to='serverapp/static/profileImages'),
            preserve_default=False,
        ),
    ]
