# Generated by Django 4.2 on 2023-06-02 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverapp', '0013_profile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileImage',
        ),
        migrations.CreateModel(
            name='profileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proPic', models.FileField(upload_to='serverapp/static/profileImages')),
                ('proImage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
