# Generated by Django 4.2 on 2023-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0014_remove_profile_profileimage_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proPic',
            field=models.FileField(default=1, upload_to='serverapp/static/profileImages'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='profileImage',
        ),
    ]
