# Generated by Django 4.2 on 2023-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0015_profile_propic_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='proPic',
            field=models.FileField(upload_to=''),
        ),
    ]
