# Generated by Django 4.2 on 2023-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0017_alter_profile_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='proImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proPic', models.ImageField(blank=True, upload_to='serverapp/static/profile_pictures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='proPic',
        ),
    ]
