# Generated by Django 4.2 on 2023-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0018_proimage_remove_profile_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='proimage',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
