# Generated by Django 4.2 on 2023-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0019_proimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proimage',
            name='proPic',
            field=models.ImageField(blank=True, upload_to='serverapp/static/profile_pictures'),
        ),
    ]
