# Generated by Django 4.2 on 2023-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0020_alter_proimage_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphFirst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphSecond',
            field=models.TextField(blank=True, null=True),
        ),
    ]
