# Generated by Django 4.2 on 2023-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0022_alter_bloguploadmodel_paragarphfirst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='mainTitleName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphFirst',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='paragarphSecond',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='subTitleNameFirst',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='subTitleNameSecond',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloguploadmodel',
            name='summary',
            field=models.CharField(max_length=5000),
        ),
    ]
